version: '3'

services:
    mongo-rs0-1:
        image: mongo
        restart: always
        container_name: mongo-rs0-1
        volumes:
        - ./mongo-rs0-1/data:/data/db
        expose:
        - "27017"
        entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all"]

    mongo-rs0-2:
        image: mongo
        restart: always
        container_name: mongo-rs0-2
        volumes:
        - ./mongo-rs0-2/data:/data/db
        expose:
        - "27017"
        entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all"]
      
    mongo-rs0-3:
        image: mongo
        restart: always
        container_name: mongo-rs0-3
        volumes:
        - ./mongo-rs0-3/data:/data/db
        expose:
        - "27017"
        entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all" ]
    app:
      container_name: app
      restart: always
      build: .
      ports:
        - '5000:5000' 

volumes:
    mongo-rs0-1:
    mongo-rs0-2:
    mongo-rs0-3: 